### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by AppWerft** [manumaticx/printmanager#1]
Hi Manu,
I tried to recompile:

titanium.platform=/Library/Application Support/Titanium/mobilesdk/osx/5.1.0.GA/android
android.platform=/Users/fuerst/Library/android-sdk-osx/platforms/android-23
google.apis=/Users/fuerst/Library/android-sdk-osx/add-ons/addon-google_apis-google-23

I got:
https://gist.github.com/AppWerft/fb5155cf42a86da847d7

I want to use it on an older app with 4.*

Any ideas?

**Comment by manumaticx** [comment]
Seems like .classpath is not configured correctly

**Comment by AppWerft** [comment]
echo $CLASSPATH is empty. It is not my first compiled module. In other 
cases it worked without issues.

Am 28/12/15 um 19:56 schrieb Manuel Lehner:

> Seems like .classpath is not configured correctly
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/manumaticx/printmanager/issues/1#issuecomment-167628648.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by manumaticx** [comment]
Did you change the pathes in this file:
https://github.com/manumaticx/printmanager/blob/master/android/.classpath

**Comment by AppWerft** [comment]
Now I have fixed all entries in .classpath and added a line in build.properties for ndk.
Unfortunately the compile run ends with:

https://gist.github.com/AppWerft/a7cd54529892d6bf4323 

```
titanium.platform=/Library/Application Support/Titanium/mobilesdk/osx/3.5.1.GA/android
android.platform=/Users/fuerst/Library/android-sdk-macosx/platforms/android-21
android.ndk=/Users/fuerst/Library/android-ndk-macosx/
google.apis=/Users/fuerst/Library/android-sdk-macosx/add-ons/addon-google_apis-google-21
```

I need the awesome module in older version (SDK3.5.1) because the app doesn't run in newer ones. 

After switching the xcode path I can build. ;-))
