### ISSUE TITLE
Questions to our code

### ISSUE THREAD

**Issue by AppWerft** [manumaticx/printmanager#3]
Hi Manuel,

1.
https://github.com/manumaticx/printmanager/blob/master/android/src/de/manumaticx/printmanager/PrintmanagerModule.java#L81-L83
Why, I read "if no parameter take this …"  ???

2.
https://github.com/manumaticx/printmanager/blob/master/android/src/de/manumaticx/printmanager/PrintmanagerModule.java#L75-L77
I cannot understand the sense. I thought the property 'url' is absolute path, why do you convert??

Looking forward for an answer, because I currently a lot learn about module making ;-))

Cheers!

Rainer

PS edit  I mean your code  in head line

**Comment by manumaticx** [comment]
Ahoi!
1. My mistake 😊 (the `!` is too much of course)
2. It only gets converted to string. The [`resolveUrl`](http://docs.appcelerator.com/module-apidoc/latest/android/org/appcelerator/kroll/KrollProxy.html#resolveUrl%28java.lang.String, java.lang.String%29)-method just returns an absolute path from the given relative path (relative to assets). There won't be a problem if the given path is already absolute. This is just to ensure that we create the File object with the correct path.

manu
